services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1005
      - PGID=10001
      - TZ=America/Denver
    volumes:
      - /home/brendan/docker/appdata/sonarr:/config
      - /server/media_server/:/media_server
    ports:
      - 8989:8989
    restart: unless-stopped
